### ISSUE TITLE
Is this project running well?

### ISSUE THREAD

**Issue by JoaoNetoDev** [feri-irawan/baileys-express-socketio-boilerplate#1]
I used the salman0ansari/whatsapp-api-nodejs project, however, it was archived... I see that this project is new, but I would like to know if it is working well, and if it is alive to make possible corrections.

Thank you very much!

**Comment by feri-irawan** [comment]
Yes, it working well, I just cloned it an hour ago

**Comment by JoaoNetoDev** [comment]
Is there any route material to use it, like Postman JS for example, or just opening and searching the routes in the code? Run at first, I just tested successfully here too

**Comment by JoaoNetoDev** [comment]
Run at first, I just tested successfully here too

**Comment by feri-irawan** [comment]
Some comments in the codes written in Indonesian language.

**Comment by feri-irawan** [comment]
> Is there any route material to use it, like Postman JS for example, or just opening and searching the routes in the code? Run at first, I just tested successfully here too

It's not in the documentation yet, you can check the `src/routeHandlers` file

**Comment by JoaoNetoDev** [comment]
I'm not sure if this API can meet my needs... is it capable of webhooking incoming messages and sending messages (text, audio, video and document)?

**Comment by feri-irawan** [comment]
Yes, it can be done, but for now, I have not added those features, so you can improve the code.

You can import and use `io` const from `server.ts` for realtime communication with the frontend, or create some new routes for webhook, send videos, images, etc.

Check `routeHandlers.ts` for route examples and `wa.ts` for `io` examples.

**Comment by feri-irawan** [comment]
@JoaoNetoDev this project was updated in #2
